version: '3.9'

services:
  db:
    image: postgres:15.3-bookworm
    container_name: db
    environment:
#      POSTGRES_DB: handin
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "9935:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}'" ]
      interval: 30s
      timeout: 10s
      retries: 5

  handin:
    build: .
    container_name: handin
    environment:
      MIX_ENV: "prod"
      LANG: "en_US.UTF-8"
      LANGUAGE: "en_US:en"
      LC_ALL: "en_US.UTF-8"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
      FLY_API_HOSTNAME: ${FLY_API_HOSTNAME}
      FLY_API_TOKEN: ${FLY_API_TOKEN}
      FLY_AUTH_TOKEN: ${FLY_AUTH_TOKEN}
      PHX_HOST: ${PHX_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SENTRY_DSN: ${SENTRY_DSN}
#    volumes:
#      - ./data/handin:/app/bin/uploads
    ports:
      - "4001:4000"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000" ]
      interval: 30s
      timeout: 10s
      retries: 3


# might add a worker node later
